name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - head
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby version ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache
      - name: Run tests
        run: bundle exec rspec
